apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cicd-acme1
spec:
  encryptedData:
    token: AgCeHHp7yYu0un1ZOE1nxBnUIk/RUfnCPR9M+o3HKcXzAtS7s/Tg5K2gzVJlxolEDy6IeSrUb04t70wvEOPDX8ZTNMaS1D6CZIexv/hgWF2fBuHbN6muQ/KV2ZzWOK+0ITvsXVAVlOJaniX5MvPcLUEw4irQk9m0zPJwaMpsLOSI7/YFclUv3lQNstbtkR4SBzM8DwLh9rp3yV0FJ2G/sJwfWwYecYitGGlz7x9D8BqaokvbYNJANVi9pRNvOacDWbbS0uJjEQ6Kocc+D28KNUrp5i3y7lnveQSvWqChL9CwpPrVvkvpkUWQPzx0s/6fu/wdFMQ9hHv/xHoyP9XwzCtXZ5WLX/uUOsnIj58H6P5eu2d0XM1PdO/IGRPsDWNrx4mJaCXI1vnN58CDRrwLcB0cC5Xp57uwGH6ItZMsR/ZZDiUNlenYXDcJ/AGYXgSUaT+ynoAdlpm67DcqdXBUe6KzBtzkNa+GxXu6SBYSyyTcEhQiBTf99VYPK5LMb4twCEU1Qb9ZMVKGKQ0TLSVRAiDjIjfl39AUN5pmkbCDmz/Zy82aWv5ATW5bo2EVfUeGQC9R2L+reAQ9k6Cj4HjEitZQCE6Z6qzTYkVuP2neRffNRj0ukAAbfEzBJFuB7K36okxa84ABoCLgdEckz8HRzVeqwnjOjHdqGmZleorbOYb8yfULBREUrnlW5HHXkkZA70d1viSn06oxOjsDjyWia0Lt3GQ7w9Nxrp2B1AODxyfjBNTzgo2ph0bm
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: cicd-acme1

