apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cicd-acme1
spec:
  encryptedData:
    token: AgCPaVVkB8ccydlPVjOJC3uLVktOjNZa+AB2fBIybw0DR+RkRrajZtLt4mF2YO9gCTy3+DnE8MA7GK3A+1VXLf0WFZymIt3/2R6xPB58IRmteXK8TUi9TTS4QCZ189V/7qMFNcp38UEmTprqEfPSlCAesoyfqgCre6AhRobcYRRtxIFqNpZUWf+RqErI5ZaUKiL1KSTPTC0pBjbjBK7MgkSJusiAnTLJ22NNt3aHn9WYiY+2v8pG+CBDOdhmlrQtc17iGNWsdR+ccmqgFPI1sENFAiS2iPJnEAkfy70oQQQ5y+jv50rJ4C+80oE9vFo7c00ctC4IM0HWBDY3DGtGPLO9jG7NiJdFJmqHDr9/i8ilBA42tq7Mraw/jsqXoE6snvoSfOP+rf6JiZa7URsCN57cDD8g6V/0PYfLaZUKWKNeDiA4iRz4tM+kUVLavfHM5B+5b96bz2tLSptrszJKfaxVpLYlnPvUwRKwwIUp2+6NSIftWLQpGTKbS9wlErkD3aE/TxEYX6ObhLSE0EgPi9HS5wdZsWhqXlxq7sU4Mt9jtQO0dwvjKrl+RijFscxH49R92Wm6DDgXFnwG+8/8GW0dSIpiRS0G/JCxJnNduB5PM+oX+CuLRYO4Rh8Y/I5SII6AX0sj14hEZTOjOxHQlJHoGUX9S1fIEZyyOLoKQSLzPrAs7MeQvhhLHdzOTK/GbC++O/O1xi3aMqoldOYDNg2UutiUo9jrDCOtBVv1pbvlmY5RhqwWKW4/
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: cicd-acme1

