apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cicd-acme
spec:
  encryptedData:
    token: AgA3REpFcten3A4W71kBKWDNlnK8IqOsj7W8TYFD67IlzUy6JbIfeFOSEv+aW9pMl4r5XdE/t0mxZi2OZbw3x1vNxRKBjWX9tZIPrS72ENPEwwsFTvmGHem4GVtVRHEVkEc9hlhHuuIpAKwNrnKCTK/kBQD3tY5+xUHToXygEyDO5m9MHVU/rfwcSNcuCn39MlF00s0mm2RwcDIggekP25LwNz2dl5Co/H9ZrVngpavNBmQZF1vFFP9ef3UQNImN1EpDdsX2gDqG+CDBuZk5LlQOWaOW2n490BXccTUT8XqN2JJgdEo7DfAC6icg1rYD6PkTSp3HZmGhfoyaElHCodygUS5ZzJkalWYNN/f+jqdCFNBfVZ2+Pu3iJJFgSUjMnxlND/Jj5XHrNctqUH7mQax4aTzQOGZatKNYfz1AGJWz0q8iYGQaNruYP3Ef9MB/2wiiPoiKFkEl2glPpz4dert1/7Jr2A6rpK/xdrAF1HlaTmOT5XyPTHpVv99q8ld7LhHfUqRhWJ2IlQmqmEp3JdXLBbtVRfmc2m8FWkZVerDl35qBYZIsByF6UCnxNZBzCmyA+jUaMh9JspTHFIrlVb4DQXYQNnHKC+r+pId2CjY/aY4aPDj9Mq2UEPeW9WU0zgBFOkN316RlyvS1H6MYEXXUqwNm6g9S7XM1PIf4X33pL8msopxIw3NzPBubKq8WBKvtmeS0DFsHnA/BZpBihZbGxzRK2s5eIByMnQbRlw3G6fqVW0/GPDYB
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: cicd-acme

