apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgBoUdNY8PkRAWxApQLNuFob0qahuP3+eQC+pskNFhtEvJjcNHZsCOFPib37BNmCkf4Th4ySIZMCqfd7SjNzfZO9g0q1eRvPWKGwjsC/FG2lxakXX/1sk9dssEGcWkiLa0A9KFMHEd113oXVdRddb7hd6k/4IECUJOXkbDpReYYlLc3UdLtf4dxwjzd84km3ymTma2NjPUliX6VzHgpSAeXMmROO+WI+LrlbvdFzl5U7VULpQiKCoRbPm1b2SFGyJ3aVsDPkiT0IATu0R3QdDQ2F5oIbLNIq4wb1kXqAL9DeHDpH5fRys+YU0IF7H8k2wUY1aTkuSq6BBVPtuSfN5TL71SEz8Mz1GxXeU2e4xPxuOhpKKPtCG65I//HGh+9T5BryiXBiJxMCerMpLDKWbcO40JR+h9491fHIw5idtMzjs0HHVtbqmSzQxPG/Kb/s8U0/64k5Z4z9XeHCyEQfv3W/tf7Ikp4m1T67aGV+Wi5FwSzNDrcfZIszqG/4hBgagrJZzi9Xs8hSlysiKoOasYBa/2ZPAWG+scKi4bceq64kmVwfEpxVcTRBX/rjRduvtPYfkGO6e1CzEma2+MdIk+it7T6GEOJDLE4qZlQ0t/kv3A7lKeH2JtdeFPjOLa7Dfr8nMLGFILI3b2xDDPIcGPIIL5Xndk+C74X6L+3JhoouscT5yoJ0S1Tn8XLVwZDAhVzleuXuy0h4OPrWKT2DGoQBdO/Cu1Qsi/VCsKeEbfGsDcqmnFw+0ptYyNvoCWTQq1iIwhL32uM4PN5aCw79MnMivfLfbBbqc0aHOAq+quCiMYEcHVLdWqOXpT0Msgee/Vt6E9nQ7LjAzOcwTKzcb3STVUtomNwHAjw0b/ysXZf5A76AMbTyu4G1Udww/FYL6b/fnCECa+D474aT8LDeN+tUPOlYadkepVRPunws5cyahhJ1DbH6tfEXRMwol34bJYh16NSNEejY8am6GfRGqzHWqCTTKuIiBoRnYsL0Mxl3xcJPDwDW9VwqcC6Cr7F89leIhWypW9j2oSLykpy4rf9i1CRkzG7S+pdvtOGv0HtQ3azOV/UpqL0/ukcHf7NuEBohy4MKcX/RA//PKlmYRmXuDR2gW9iVJH1uBShZTc5YLXzTRt6sFfPQauAGgJAG8x08QPQJKV6euUbXzc+zcVtAcgUcU7EHjUDoa6HvZ2fq6yYr9Z7Ssmx7JyjvHyltbAMQlMnkEnVapefZZKzfWLPDf8FDmAoHEQ8J4AVIXNOPOjLUU2I6uMo4MsV5niZcBnEYrNtYlCRC9gwyTDxCvD0AkcvDJqPuyCJkExweE9Wqexz0Qy9FrqN7FnZSaTmYqllV0BWNHr7XBAAXbqn6H573f7JfuvRfSlJw4kMZ/hBVxSi7otsb
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

