apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgAWimvS38wgOGkQcKrCLAXfeKZkQ/QBojpjWYuFUYVDmEiHexFX4OCYnuyo2xFAjtYRfjtgV+A8zM3mlv0mz7qO28pfCqldyVrCLpuUrWRuOwrJ0zulABj+bRgEceKuU3KQlJ5IsI6W5zBxb9EVfTumFf97gPG6nCn0kSo516QvXJ2qqToOcDGA88N+0AUMCBpDSJvPh+Go6nxvbJW0xOA4Vy+n14zFAV25eyRhjvCZ8rnXMkR3t+2Acv2WMrh5F5XlEhVTP/RkEsLT/XR1Gqrskcb2xN6nxniLpd7rggGABEZwZbyfIqZ4FtSgUg3zkw7rs9W8HsOBnAlx55KDWAswjnxR76dfAyH7Fo7aHR3mVeuFQE+ie8Hv0ckcLQaWLn+GEHGMZzjzNacmcBapprTaqF+x7Sc9bMgQOuB1L8aOFIt1EqTViJ6tRcpUUcU/EsSQ+FX1inxagLJ3RnNxbMpmA/+sT8sqNhQbRwRvmxNVPwiBa+WG7zzCAsjB6GhMKc7S5gAtBTf4vqV5wjbR7/ef/NgNARd0g87zfx/rNkwS57N9c8Mh8G7K7n8ofnFHigCVuvoEj77LqTkcYTCwTkssa6O80zp3YyudH3ooi4w43BOODxy2b9xF/5417foT0CpE3C68XuzIbLE2+cpXmxe4/gge7m8Wyjh7t5h0yugUtgScX9tkWLznKRUQVN581h8ywAPCyh2nPrmvk55ohGToOyD7+wP+8NnOHmDBQ3FhAB+v2hXJPrzCQTZmoEdeF2xTz6h1hlTy0rHafOrKd8boQQG/aX886E3AGuW6oE1qW9xY4dwMA7ZWkcnBi88NFqgyy4rpaQil7GOVRQCfXZZZFqMFL0nfFTSM2Y4UQpGcNUFNOs+t/EOxai+5OrbK3XptrMQrwSjS+nDPvRpEZ+arlIcJmACdTsyr+00A9ql7swzMx2r/khgMdXjD+3068OSizbiYHx3PHGcLQPak2gQzkCz7tyWdGykD6uUYaqcLCYajjMH1KJRCe8pkq3X/VUgbrnstknrcykTYOn9zapyRArQCn9laIyOsRaXuDsvwi9nbawGIeWqm5hwuTm7PUZMr2tPh7wbNARiuWAyTQVxycwlpPj3VrskJ+f3xF7+XyXPlHWdcmfXjw3N3ysIWjTmQ0jjFj5dheeY+bFty8/OqejmABuQ5i4D4m+c+buj33vePS2mBuF09HgF7SOauA0QU5KSTvXGGb7r/gcpD4ZtjKAVkq1KhkWozpz0U0MvVv9zlYUMU5wtJ5KqcgEw84XAWU7W/8SLBjTtwMa0/TQ0amPJnzsu/7kX9rvpt0r8Hw9cZzJHHQ8xnc8v+4mjqDPPqIzfDMIJcknyTyHTIIcjk6cVLdhOmZYDJiWOWCaGhj8JPVMGS
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

