apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgAIXirNmkPPNKsjVLbU4xNQT9C4FbhPLpdUa/uXcRkRdDsu1H8ao1fFeuTUQqULqOt9LAtd0kLornJOF8rTKEiD4ODFvryyUZN0ka2zJ3mbq/gfBFn08vAy0Ti9pcr3GWCjxqFwIGiueCQN15zCp/0S+hcJfB4by3wdCKOZXBEL8iTwWMm0seagoFAl3eBGnGm7IZygyhc43II59ryvIFBFGKMBBW28/UatMqB2BArxTvL/64pGGcMEwb5LL5PLdxk/Uzy8wEdbLBCeDgBEoDwrmb2BEXCk3r18IXyOQbpjwka4TrIFCNFn/ACHKAW3MLQ1UbkdaZMNHDxVP11+oX83Wa/3WZspLppY6xcv+oXk+YCjGv0tlRFLerM8+gln/dYdEqxcMsdcAOON7e2UMRRYrxX9KnWjk3OU/gTPhrNdCvJINZZDcQB7rlZjex7Wu7VjBPd1Lw9AUkk8tY5r9dv6/GGT8EKBjTQClZN+6/nnqa+/VmIE3Mt3+yE/doe4gNcYdEZjIM/omHsDI62mpLEdDQ81bXHl8vsCjOSooctf8hYermTE8ZbAQvYV9Nu8gXRVcW2lwMqP07irlO5OLIYSFRQO2dTO4zDbhpwm7zKeyePiNfCiekVzSeQ6fRc5q6Rs6T/86EDtgsAEwyCONWRHzasMlxLl3Ou9dOVLo7C2BpqbwVRry2ljwvUxP59pINao6bMD8hSLnMnyIxjronKs/iNujm5KXe9+KRJ2jYzrQyJygfbk44/zjvSKNRYUZn4zgtdi7OriyF0LjceRN1KLACtyiFCznwsuyCaI9NNBCEABqsGaqvgRL1jgCC5jGl5Ez1DxMRm05jy2qezJAW5tfNC0XeYk/3o65D9RzGXwdmITUMHTRcyLMlA+BEgAnpeoPlY4sf/PPS10JvQ5W9ozUuNsA2Kcyf6TTC/Vxqv4B5eW2QWPl1Sygm/t4PtxZFbHK8Ds/7CPtEPtCDVzPE2OGj7qpWLxWJCDq7sHVeZlPW2yuN93g58z1UCG3gs98WNXgSNO6ZuuWguT9bBETQ3phFBYAvckzT9hSavA9ZCzHb/OJ+XNwAac2cnHe4YZ3YkKhC06ncit2RPYCXRJcS7KOkblx2lUdcjvf01s5gISwEUy3UQYfvcczjFecGmJ9ybUBLQXNID/WsrOAmhhH3l0veNl5Q8L+P8b3NvUyxpSJPDDqszyZP43v7sLX5c97425IBDKLkuvpzu/fYoPY01DED0FEc4EjjKWnyf0h2L62yUCUima9q1Ihkp3wjE5MgdoA5GoCBPvVDWpEpKXyxPWWbAKYZgx/ileiCWXYbAGEyqVGBoMzcKKOjg/ckVQVU1h2IHPkYWwI/Sdck9/9Tes151/Y344xyRx6xh1J3JM5WqietSb
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

