apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: apic-pipeline-git
  namespace: ci
spec:
  encryptedData:
    GIT_PRIV_TOKEN: AgA8W6TL9M2shMoW1QrRqeKZWdVkkBV5USQwRLuwoUtAA5PqjqW7epR5IMLCQrjOVhdaWXM13PJXGDVoEjH0QdOZjI+Y91W3sdSVjIU0l+tG5nKxIbWSW1yN06NdUIDD7PgcnIZss0OexFjsz6NjEbAxF6AZa1dacVPgxjPFuwBmMZ5UepGaZuQj7iD5zpIWoz500dd0WpJA1cPft6AldxiFuzX0A6uPPrJAhn4vx7y5fJ7ReamYekEBC/WtSxgFkWEZk9/o6ggB7ePDThdFdzcssxnsTQrBelFhMpkQRs/JwUmAIlL5LAPeRvPuRiXN8mE45iiuEuVGHasuhHG0DNQz2G2lD6jKwTFZH0MzNw6rwvy11KARbl0hP9G79fG0DPW8Sqf1oNTLiq1CUM+wRPVV9gmZeZUrTCxm2sC9YeO9ouVqi3O59U/GZSytZpW79DU1nMBVVy5HwPBQP3q9oPXGBWm1Wg0ZfnuIxd7K+N3BTqWxLDmNKFeso2eFXrf3m22N3Xsk4Oo2c3oU3CoNwS0KXyoi+yBvPp+fHwWB7JbAXXcTbdNjgPLVYctvDdqXcVumXRuaGONS/QJO7reBCoHPxqFQDtCSl9w/3mGSGD4e7lt3MG85wyfImzYWXkgBxV+waHn/5CU0jG2GexgJFEyt+ryt6ECC46mPXuEH2fsKpForUlf1/rmylE5nSY24Giqeyn2TvzivrMtLDkKcPQIwQ/o85Piy7ahFEy6XGq3fkNXg5ezl5ukX
    GIT_USERNAME: AgCkF/e4Ev53PYQJHwM10OjPh3Pat7oiUD8juxCo3kEDxuhD6aj/kb3yngymhCIsOSZX+OSkt5ObUYSYrdCcWWo8PwBiLiMyHmzirthepc0A8ky15eNFmunSxmdm3vnMIX1e0CVWYR9Yc8OmvZs7DQwJjjG4UnVO+S0ghzdvtERaSdbjahInwepzI0k4uiqKIHChp6N53pQ5vleh0kQVNjPQmNyNAsOT/Ed/4eHN3eXMm8orufo6PLsRKj311mDKdFTFrp9QjIAKPytRFzxFkUDkmG3l1WQMkwrbBcNMYsIpvl5pU2PrFbyyZrSRmAIDYQd8QRRl6fOzmUPR1ICpdQB8vmxV7foKn6c1Tu7E7POdb81pc/lk7ptgP4c2tFi3JLUA6AtZ5CPaatOfWiRDXKdvdxRKG+6Kcoarx7vmZMfspKKGaCtHGCSODtD8uBrX1K8D+4VWHnO4lRIOHzYoQhHSivfaEFrLu/7zARul9W9nvTPNyqKP94CgbfEQwBcZXoowbZvQ4Y/hQsXWtxfoYbaMLwUuN2Tj+5gaerih1DbJlOsn8gtohI0FYAd9LxImul8CQz1cW0REyqFQcSEfkP+iarFaL3r3hjLSoCKUneR2gCheXTOTyYfoH6R+BD5BIqBuJZR57KxOdoyr4LPZERlJXrquW+xnPPjeJXBBiDA6XQ9O3tJeRbl4ayaUi9+/MlTtUIx8b++ZzwH4FAY6
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: apic-pipeline-git
      namespace: ci

