apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: create-customer-policy
spec:
  type: policyproject
  contents: UEsDBAoAAAAAANyUmFgAAAAAAAAAAAAAAAAXABwAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9VVAkAA8BRKWbAUSlmdXgLAAEE/P8AAAQA/6Y7UEsDBBQACAAIANyUmFgAAAAAAAAAAPIAAAArABwAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9iYWNrZW5kdXJsLnBvbGljeXhtbFVUCQADwFEpZsBRKWZ1eAsAAQT8/wAABAD/pjtdjjsOwjAMhndOEWVvU7aq6mMBRqZygJAYiEidKE4LvT2pCkIwWfb/8Fd3z8GyCQIZhw3f5gVngMppg9eGn/pDVvKu3dTeWaMMULthbF1mto5+9pCcBGEHF4Og+Vs4yiEJZ6nugHoM9nPvYfBWxr/QUpyqyUm/R+2dwdjeYvSVEMstORNkhg4J1Bggj85ZymlSVVmUhXhQLX6yC6dYHyZ88eV/AVBLBwgyw5h4pAAAAPIAAABQSwECHgMKAAAAAADclJhYAAAAAAAAAAAAAAAAFwAYAAAAAAAAABAA/UUAAAAAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9VVAUAA8BRKWZ1eAsAAQT8/wAABAD/pjtQSwECHgMUAAgACADclJhYMsOYeKQAAADyAAAAKwAYAAAAAAABAAAAtIFRAAAAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9iYWNrZW5kdXJsLnBvbGljeXhtbFVUBQADwFEpZnV4CwABBPz/AAAEAP+mO1BLBQYAAAAAAgACAM4AAABqAQAAAAA=
