apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: create-customer-details-rest
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-KZVS-2G3FW4
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: 12.0.11
  adminServerSecure: true
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/ci/create-customer-details-rest:1b6dc5cc03511eed34e2d7a82275208143a693d5
        imagePullPolicy: Always
  configurations:
    - create-customer-serverconf.yaml
    - create-customer-policy
