apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: create-customer-details-rest
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-DMRW-D3HQHQ
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: 12.0.11
  adminServerSecure: true
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/ci/create-customer-details-rest:2a250190fb3c3d2e634acc0831aeba25a11e4836
        imagePullPolicy: Always
  configurations:
    - create-customer-serverconf.yaml
    - create-customer-policy
