apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgBgrNxiR0VHFOeJlS3mJJGOyS4J3ApjCwbdPJwLH8uuFgo4fjyWoSxHZmgS2Ws0iBa22KYvtlClfm9ItwF/ldJ7TvzhM5MU5Ya3vFqfVtO4fa1/5EelC9vFkoSHDHzRx8H7X8fDGLE329qZSd7Z4ufbZjMjIsi5xmB+K5n/tySI7/FbapTC3COEytEcaTP1sbSri4ZRbvNePlBLQAF+nh6rMycCN3rXDytdQCsuD/2/D9tB8kBPX3SFCpL6LrMG9Yv9SKXiECUn3GEKVQfnmRH+gcFvvMe5f0inW4n/hQwtSuKc3pKUDYl10G3GO4l3FCkjMlDZte5Rizb3DxpwWeJlVABWpdugg0itipOhKEgaHmxYzVIBHqQOZIszKGm5GNR8ckSSUZTPURRcIcetCGmLB9/29Frkx8z2lWWXRTgSGukVJaTDIv7UyIpA+HlFpZAmoLgCaZK8jPCnd3z7A2BK1DD89P1QJRecXAtlL1lFV9IyzLJeED3/TIlZ2KghN9tfbIvhc5j7eQREfTkEOoA9Ezyvc4x8kBvRokqOGJcriulBANe05+2Dshgg6zcWLMdwQZojCvuKStQaCsgD16IFhIjWaCAvARTY7+nHWaI8e4Glhf1Oa9957KuKvgs5ycABD2qbPAoMJSTOiGeo/YFAVRnrS7OjWk5PeUDLZ44Ry/j2o7DdA2Qrx5XhUHU7nMfNwGiYWBUPu7KeuvPGRUkRfgnFQQHV5Th3sqBsr1231nPg++eSIQh5
    username: AgAMWFOC6HYDj5932MfCZzLHmBjR3WlF8U1DEOBfjeHFCJUKcBSOyfIGfGRPa3uQ2ENZE0lnFaS39H5cyPlp1aGWVZr8sFXTpcAN1G4Oh1ARw51T+4fSiGxuzjdEnPmQW/4N2qlrXzKwhvTnfEIjy6ayYiJDN5Oa1KzpgX7eITqGO7gEVlmQ6mr9I6DBtrfvp2ZnjuSWd8klHC4jl4KAUAVKgauKddLO99n+yP5qDqx+yIx+eA4e+uyJrKxefiYnkQ4E12tqL8WlbldSviRJA63jZ34vYichbI9BsbsJspuUH6774+OQFnGLg1NEb91lghJU68pPlRvbqgiOEZ0EYuvogXPNPzSm+TiXXGkxJmnuSqIEx+E5T8i7cr17qpY7TULGER8dG1J4wAmEMqMrJH0c7/U6nWrbF0PRJFWcQbDIoeoWFp2o5b5xf4g1aknKG0/xgQwsYXhaBvX/4Yi4Ww5X+zBaNTT73OkAmHafF/i24990m4/zTVBVRXlW+FEzOpLuVTlh/IVLG2QpeZqYctTpvXsGcVrOrkFtDmrW0gfP01VExFoxI08Z+rdjfir09QW+YRULDL/7L2/zVE9ZLIx2QJ5m9SYOOynvesAcKzzEkGjF7dOUabO331pFd/b45aQ8RX+eGjvA6Mat9NO6mzQtwZGU3Z2KHD4PFSzVbg23waB2W5B5eRgvcamJw7f8UAZXHUeJntBFdPf24xoE
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

