apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgAg1Gf68y9blWpuf1+fHg6qPpWfMUdLkhsFhgkxdxMZOLAgQBFZfXDBBiGZAJlx1pPUlOvsnj1Fzf74zg/t8X7KLyTCUh0YrnRWQJLIwpX2Lb+SMlVNHGSz/wAT/xExBb2vlViYHNHsFN4M/223V0ZmIwSowlMIstSQiSaEHvLniXV8Xv3PkEYgmFayWTgX694IRn4BrxSQKR96fvhlN5M7hOiDIe4WvF9aOCo+Qqf+Ow9u97DWVi8Qw5CYjzw39CFw+AVht6CLGvfMRJwxzj/6fDGW9G+s9Hq8nMxdeVvdev3jXfXtqsdVHgtT3GHFVp0IaThBUA2ltfc4rVkeBVMGKuCxguLyIhYk5ZTmqGRoSZOfDvf7ScIQtAW2v0if+rmY5v1EffHv95m9LTUzpEN2/+V9HKzoEHwmFOJc09G1NFzA+PK4Ia2tTRf36lq8zamwY0QXwPwHj+S/djARavJQaTPTz+j0FQJxr5bTfTaXaBOR40TFVuMDHhBYFPHhY3zto7C7cgOaz7IS1B1aVH7TJwJpqpbe6vvdvk7GtiA13VyoAf4rnCOlwYd0oXd+YH47ECFgYU4t6e1btFq3V0aR4GVLRlCr8zFwp5slRH0QTJz3CceiNdh8NI+TcMt04m0NQLCq4Pi60cTrNx5jfeYvx3cbQFcfHRmHr7nISwrppuSgy4JTcDA6EaJPr4pupeC/3e66IfYnTEY+uFmmqx1hh9Ccx1IzHyfgla81OUFmaavDYaVxjyNXNWOt8E8UBktw3BndgNr01/379dJwEmxf1jo9hSIgURl4qPoRr4TaIdtdeFEVkO2N4GKZUKSJy66Y/2uSDXmQp5WuZQOlJEUrsxoQ/kjV0OBuGYbBs6hWbpuoMcTt5KPm3vJH80jdqKSq85VIjL4NaoxW2GHpshrP2YwzY/BdpGK04hDIYJAHAQEPtnE3gcPuaTbNale2GYk=
    IBM_ENTITLED_REGISTRY_USER: AgBlSBXC4g9DOq9+BsS4lLpbaSWuevln5K/zlBFPWJDIarMPx6ApLdDd5kGuSoVZpszb7g4ISHmtQlx/7pDVkvzVxzO5Omuo2PhB1eqm0dqNxarJaMJDb0Y5f91zCDo/jXdipjFVD9/fQzhelIWGJA+s+2yZVC0GTuoZa8h/uAAX0YqE96ameAxC3Y2mgrh29buWDNmFsOHae8FtmybGiGx/AeF5mHrrqE11azTy6zBWLzWygD8mBZGwqUPNNU/Oc2v/ZEbCPpJnvL255N4DNvSKxZGTB2YkXqjs74PaQIOkznj0Vp0XYa4PKR874HJAeoahKlGtNLOo0hWplMHoGYMlWlCZvikqrA+RPhuZe2GD6fq/dPEz6eX17S9V9LvV+j19DW1Ywr33tDOAg04aKYK0XrBjq+DUo2Ls0mJ3bblVTaE4FYA9LdRqwY2A8bFQ1JWGTJQkufZ8DHE18s3iQdApx9S1aZ7xAaXe57miDpve+7fBvvhebFp5N3oQr5KAGMo52OEfDSZqAaa3NNG/tbo9EL5LMiVlMGqnLGZl60h+yKZ2LTKKk9wUXX8zT8co0Mz4NgtLs5o9BA7gp1mzIoq4cc6YpTCsl1bwQASFvcUfPM0fmQqMVSpV0nSdb92f8g+JN7ufmms41kblZZdBcfivBtuRxy6Hj3qP75Ot0dMISUIZJevgZ3YSiq25VnjgsBtMgQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

