apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgCAGiLwiPFOEwO9YrI3NKa+SdsmkOiWrmSSgOXCjk9+3znfC34QJEnu0CYwp9e3MDOYeuAUbtd1rocYN2GO5GBpLEp7UMzfZQXkDMonbaJV4M53Mj4hvXoJ1Rknpnb1fagRtpnxEnXhACB4WXnU7/PWX9TcMU0QLUxCO5pZE0iL28E4DfoD4+BVLo8puhxtf+FXL1Xabjst5uPOMOdAHFjXH2lkJlAREaMHy6wXLEfI7IewbOOqtuVQsoZNwlXsnTNzEQHKAR3CgZEkw97thLaiQ6TaMBZSVf0hgH56Mp47BJcO+L5fFSXnXL8M6fg1J2FUGEgw4vzdF2NpyppRzpIgXselc2PF6kyK9T1ZZsZI7r2FLJssoUXmH19NqtoPQDTCrspnb7Zhx5UNoZ/ZFXhRnCR87e6Hhz1V0P+ACoQEwwKE1aEPPKLzdPFYgZ9nZMkxWI1JaYWR/cD8o5kmizTwlzi8U3XKCWjG5YGpwQrVcA/PD7txVbyAM+hbPI6N01yuRei4EleweTAknLnz7cy1lI2YBE40+OCcXrQn11fr3hYLOd4C6DfWT/h500cb/nwWHAu1H8WFHlt2Hh/FlWntzumg4YRJO1iBCsMkQDyoZ3FpuPq02xBjCZiKXlFBPS5Zs6fKAxg6IAlFaQ5b+Qpu6jDSxi3fyD7s0hgIO3sSTGnhUYzFnyzlM5lTYq5Z8yACMxm3g/KCf0KVNv1D5h0lWLtzsxmJWuHqU5GmpEnX8U5lMbjUFdDJg4e0pFbJyUv9olm3pC32pkhUm/+LbZ2+AQww71S2HOMkB2yz1MdaZ+5M2SzJloXYTk9LNhI0713dDnjab8N1hf9McWEux4e+dUB9CllVlx6hGKoX5yMwnN8eF5kBvV/MbmLRbBDq59SocogwIc3AWL08Zcafh5tfTonfs9VNz7yCmzDWtRdVXhINSyGG/bYnShTx16eZ5rRYVkKqlWB72W/7ThjT/g7UYVH+ioKcujoMvkDBMNnb1RAirvoi3KOKaHK5tcjWWqOApurq8+Ora5DVOtKM9lMphyhCSbpz1zBGliU6dseKp5eK9zcpHH5F2h5eJneKJrJlwku1IlOm5BNYsAjXZnLfHUEH0TcrGPLfApa/I4E1LIJ8nL/ul3L42Iz8yL9Jpy3VXLncp09mwYIecx0S2i1ghkrzkCl0WJBKOs/CVWV2kMsLPWM6bXMLSmbFhNcD25udmOb5Agax/gp96EaybHulRjy98cYtmJWZE3AMnh096n+cNhEBLxKJuZGQBKcqIeY7shfjhcEVm0PF93J1+dQxVTARcLRdkX1eb6IrIXen5uFNedpgAuRV8Rv1bPJt5JM3XxWSnLAUkZa1bhWUAfK4JwXBFaLO4Na3vAoxEndVsI3ybWEO
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

