apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgBS/7lvEzZZ594e/W+bBn/9XGvE1l5MfhwUt1T8AbSKog+lSLbPpsiLJZrA1cM6SYEyhoHlTpckMDD4mfxHH5Vf9WppPq1UEWdFie6CysPmHE7r1WUbcUP+f8qU1HRjevH7TAJtHMnE9rWKVaJM3mPf+HkNfo3M2ewjXlZw2l4Ikj0N8fgXMAcTf3HnXbslXpd3x8daSVPrDQ54X4MaE08/gfF9RjuwVJkKSzFhZ4OWP3/spAVADuWV7oTRWWICGO8YhexH/FReFymKCgjO+Qr1GI5oHl0ax9PDZsF/RHjMw0KOkiUZQBiIUtdK0I+rfSefAH2nasyDANA5kwroHMXslGtLNTK5BLbBTaHBO31GWXL4JoFtGf44fEhCqD8nnuZcuqBwD+F0UONVfOoumf0s3ncIZ0Y6CbEPw6QOhKoYjKBbah70/Hc+QBPcppvdDh6x9R4udfOBvN2XUcmAwnVTm91W4OdYy5WIJ0BJfA9fcv3a1EDoInxU9gc+9LOFgvsyrfgG0LiI7N15ytPLlUxF+QbH7RclFzR7b9Yyxd5DKE+AdpsMLfxXiiIaNZnaMhlTcJNs2xFPd7XP60d/wHzGMuSxDNAce6Ta60lmeiOD/SQRfnWaAebbHy1QP5X2OnHiBf1FLS/cTXN1v+766W5/HuTO7M7xcUSg4AM8b2q+O4fQ4rwVfuCMjuBTpsFPWKhmBALay5R1zsZsjKKduXYeQApaRh7g/8h6O12KW5dXNB/67ZDgQa/ljXO5HxPxw3TYknSJLZP2nLy+5eSDHiUOguTlbAQp1VzaA6Jep+fUBOLPzh3zgCOXWygpTu3ZFVAe8hH1SBHVdGbK0SfLGCrj+tEeLQ8mTp3vEzGHC/bPzzOWZ2mVdmiNBjb9noBmeugBCoBEbf0Jav8G0Wd507F6WccS7rwvry5Y/t44Cx7gU7vgA745clXvEjCDnwXc0v9cIpTAZ4wXHkDTi4x/ucKaEP4zJxj8FpV92oISeHftL3EqDTaH2YuSVoXH7h4GZ+ntYOmJZ2R+5rJisVoZEq4aQk6otsGccl9t2n1ZI7nozLw8GfAm7iKlrt/yToM3fEe3/h3EKk1QGLXB/XLiiwrvKcnVYFG8jbEtsviOe/BuZ0ZZUUaeBYJywWo0NZUcs+8XKVPGFiIXwJpvZgGJWssjeCZuJJz6L6H9JPq7DrseFOtHhN8Kp3XKXVsegVJx/XFWbMlRUErrgaXaok5A5bf2DMBdRGFpNIoKaE86mSv13/sr1bvbXYIKjWULkivh4MW4Zf5Z5I7Faw3sL5hntfJ776GUZiZjsGVYGVXxyRUvFtZLdRjuBeSQbaq4kTw+hrM9fctmdcACvInnTSLZpikefw5yWUWWb6LSQA6cj7Q+C5CmUkVm
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

